version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python vfg_backend/manage.py runserver 0.0.0.0:8081
    volumes:
      - .:/code
    ports:
      - "8081:8081"
    depends_on:
      - db
